name: Build production artifact

on:
  push:
    branches: 
      - "main"
  pull_request:
    branches: 
      - "main"

env:
  SSH_AUTH_SOCK: /tmp/ssh-agent.sock

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: staging
      url: https://p3k.org/rss-staging

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Setup SSH agent
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
        mkdir -p ~/.ssh
        echo "${{ vars.SSH_CONFIG }}" > ~/.ssh/config
        echo "${{ vars.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

    - name: Build and publish to staging environment
      run: |
        npm ci --ignore-scripts
        npm run install:local
        npm run deploy:staging

