name: Build distribution files

on:
  push:
    branches:
      - "renovate/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v5

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install and build
      run: |
        npm ci --ignore-scripts
        npm run install:local
        npm run build
