name: Publish production artifact to staging area

on:
  push:
    branches:
      - "main"

env:
  SSH_AUTH_SOCK: /tmp/ssh-agent.sock

jobs:
  publish:
    runs-on: ubuntu-latest

    environment:
      name: staging
      url: https://p3k.org/rss-staging

    steps:
    - name: Setup SSH agent
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
        mkdir -p ~/.ssh
        echo "${{ vars.SSH_CONFIG }}" > ~/.ssh/config
        echo "${{ vars.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

    - name: ublish to staging environment
      run: |
        npm run deploy:staging
