name: Publish to staging environment

on:
  push:
    branches:
      - "main"

env:
  SSH_AUTH_SOCK: /tmp/ssh-agent.sock

jobs:
  publish:
    runs-on: ubuntu-latest

    environment:
      name: staging
      url: https://p3k.org/rss-staging

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: 20.x

    - name: Configure environment
      run: |
        echo '${{ vars.LOCAL_JS }}' > src/local.js

    - name: Setup SSH agent
      run: |
        ssh-agent -a $SSH_AUTH_SOCK > /dev/null
        ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
        mkdir -p ~/.ssh
        echo '${{ vars.SSH_CONFIG }}' > ~/.ssh/config
        echo '${{ vars.KNOWN_HOSTS }}' > ~/.ssh/known_hosts

    - name: Publish to staging environment
      run: |
        npm ci --ignore-scripts
        npm run deploy:staging
